<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LBL_ADD_RECORD' => 'Adicionar usuário',

	//MyPreference Blocks
	'LBL_MY_PREFERENCES' => 'Minhas preferências',
	'LBL_MORE_INFORMATION' => 'Mais informações',
	'LBL_USERLOGIN_ROLE' => 'Login de usuário e função',
	'LBL_USER_IMAGE_INFORMATION' => 'Fotografia do usuário',
	'LBL_CURRENCY_CONFIGURATION' => 'Configuração do campo de moeda e número',
	'LBL_ADDRESS_INFORMATION' => 'Endereço do usuário',
	'LBL_USER_ADV_OPTIONS' => 'Opções avançadas do usuário',
	'Asterisk Configuration'  =>  'Configuração do Asterisco',
	'LBL_HOME_PAGE_COMPONENTS' => 'Componentes da página inicial',
	'LBL_TAG_CLOUD_DISPLAY' => 'Tag Cloud Display',

	//MyPreference Fields
	'Role' => 'Função',
	'Admin' => 'Admin',
	'User Name' => 'Nome de usuário',
	'Default Activity View' => 'Visualização padrão do MyCalendar',
	'Default Calendar View' => 'Visualização de calendário padrão',
	'Default Lead View' => 'Visualização de Lead padrão',
	'Title' => 'Título',
	'Office Phone' => 'Telefone do escritório',
	'Department' => 'Departamento',
	'Reports To' => 'Reporta para',
	'Yahoo id' => 'Yahoo id',
	'Home Phone' => 'Telefone residencial',
	'User Image' => 'Imagem do usuário',
	'Date Format' => 'Formato de data',
	'Tag Cloud' => 'Tag Cloud',
	'Signature' => 'Assinatura',
	'Street Address' => 'Endereço',
	'Password' => 'Senha',
	'Confirm Password' => 'Confirmar senha',
	'LBL_SHOWN' => 'Exibido',
	'LBL_HIDDEN' => 'Oculto',
	'LBL_SHOW' => 'Mostrar',
	'LBL_HIDE' => 'Ocultar',
	'LBL_HOME_PAGE_COMPO' => 'Componentes da página inicial',
	'LBL_LOGIN_HISTORY' => 'Histórico de Login',
	'LBL_USERDETAIL_INFO' => 'Visualizando detalhes do usuário',
	'LBL_DELETE_GROUP' => 'Excluir grupo',
	'LBL_DELETE_GROUPNAME' => 'Grupo a ser excluído',
	'LBL_TRANSFER_GROUP' => 'Transferir propriedade para: ',
	'LBL_DELETE_USER' => 'Usuário a ser excluído',
	'LBL_REMOVE_USER' => 'Excluir',
	'LBL_MORE_OPTIONS' => 'Mais opções',
	'LBL_TRANSFER_USER' => 'Transferir propriedade para usuário',
	'LBL_RESTORE_USER' => 'Restaurar usuário',
	'LBL_DELETE_PROFILE' => 'Excluir perfil',
	'LBL_TRANSFER_ROLES_TO_PROFILE' => 'Transferir funções para perfil',
	'LBL_PROFILE_TO_BE_DELETED' => 'Perfil a ser excluído',
	'INTERNAL_MAIL_COMPOSER' => 'Compositor de e-mail interno',

	'Asterisk Extension'  =>  'Extensão Asterisco',
	'Receive Incoming Calls'  =>  'Receber chamadas recebidas',
	'Webservice Access Key' => 'Chave de Acesso',
	'Language' => 'Idioma',
	'Theme' =>  'Tema',
	'Time Zone'  =>  'Fuso Horário',
	'Decimal Separator'  =>  'Separador Decimal',
	'Digit Grouping Pattern'  =>  'Padrão de agrupamento de dígitos',
	'Digit Grouping Separator'  =>  'Separador de Agrupamento de Dígitos',
	'Symbol Placement'  =>  'Colocação do Símbolo',
	'Number Of Currency Decimals'  =>  'Número de decimais na moeda',
	'Truncate Trailing Zeros'  =>   'Truncar zeros finais',
	'Default Call Duration' => 'Duração padrão da chamada (minutos)',
	'Other Event Duration' => 'Duração de outros evento (minutos)',
	'Calendar Hour Format' => 'Formato da hora do calendário',
	'Tag Cloud' => 'Tag Cloud',

	//Time zones-Dont change any value
	'Kwajalein'  =>  '(UTC-12:00) International Date Line West',
	'Pacific/Midway'  =>  '(UTC-11:00) Coordinated Universal Time-11',
	'Pacific/Samoa'  =>  '(UTC-11:00) Samoa',
	'Pacific/Honolulu'  =>  '(UTC-10:00) Hawaii',
	'America/Anchorage'  =>  '(UTC-09:00) Alaska',
	'America/Los_Angeles'  =>  '(UTC-08:00) Pacific Time (US &amp; Canada)',
	'America/Tijuana'  =>  '(UTC-08:00) Tijuana, Baja California',
	'America/Denver'  =>  '(UTC-07:00) Mountain Time (US &amp; Canada)',
	'America/Chihuahua'  =>  '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
	'America/Mazatlan'  =>  '(UTC-07:00) Mazatlan',
	'America/Phoenix'  =>  '(UTC-07:00) Arizona',
	'America/Regina'  =>  '(UTC-06:00) Saskatchewan',
	'America/Tegucigalpa'  =>  '(UTC-06:00) Central America',
	'America/Chicago'  =>  '(UTC-06:00) Central Time (US &amp; Canada)',
	'America/Mexico_City'  =>  '(UTC-06:00) Mexico City',
	'America/Monterrey'  =>  '(UTC-06:00) Monterrey',
	'America/New_York'  =>  '(UTC-05:00) Eastern Time (US &amp; Canada)',
	'America/Bogota'  =>  '(UTC-05:00) Bogota, Lima, Quito',
	'America/Lima'  =>  '(UTC-05:00) Lima',
	'America/Rio_Branco'  =>  '(UTC-05:00) Rio Branco',
	'America/Indiana/Indianapolis'  =>  '(UTC-05:00) Indiana (East)',
	'America/Caracas'  =>  '(UTC-04:30) Caracas',
	'America/Halifax'  =>  '(UTC-04:00) Atlantic Time (Canada)',
	'America/Manaus'  =>  '(UTC-04:00) Manaus',
	'America/Santiago'  =>  '(UTC-04:00) Santiago',
	'America/La_Paz'  =>  '(UTC-04:00) La Paz',
	'America/Cuiaba'  =>  '(UTC-04:00) Cuiaba',
	'America/Asuncion'  =>  '(UTC-04:00) Asuncion',
	'America/St_Johns'  =>  '(UTC-03:30) Newfoundland',
	'America/Argentina/Buenos_Aires'  =>  '(UTC-03:00) Buenos Aires',
	'America/Sao_Paulo'  =>  '(UTC-03:00) Brasilia',
	'America/Godthab'  =>  '(UTC-03:00) Greenland',
	'America/Montevideo'  =>  '(UTC-03:00) Montevideo',
	'Atlantic/South_Georgia'  =>  '(UTC-02:00) Mid-Atlantic',
	'Atlantic/Azores'  =>  '(UTC-01:00) Azores',
	'Atlantic/Cape_Verde'  =>  '(UTC-01:00) Cape Verde Is.',
	'Europe/London'  =>  '(UTC) London, Edinburgh, Dublin, Lisbon',
	'UTC'  =>  '(UTC) Coordinated Universal Time, Greenwich Mean Time',
	'Africa/Monrovia'  =>  '(UTC) Monrovia, Reykjavik',
	'Africa/Casablanca'  =>  '(UTC) Casablanca',
	'Europe/Belgrade'  =>  '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
	'Europe/Sarajevo'  =>  '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
	'Europe/Brussels'  =>  '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
	'Africa/Algiers'  =>  '(UTC+01:00) West Central Africa',
	'Europe/Amsterdam'  =>  '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
	'Europe/Minsk'  =>  '(UTC+02:00) Minsk',
	'Africa/Cairo'  =>  '(UTC+02:00) Cairo',
	'Europe/Helsinki'  =>  '(UTC+02:00) Helsinki, Riga, Sofia, Tallinn, Vilnius',
	'Europe/Athens'  =>  '(UTC+02:00) Athens, Bucharest',
	'Europe/Istanbul'  =>  '(UTC+02:00) Istanbul',
	'Asia/Jerusalem'  =>  '(UTC+02:00) Jerusalem',
	'Asia/Amman'  =>  '(UTC+02:00) Amman',
	'Asia/Beirut'  =>  '(UTC+02:00) Beirut',
	'Africa/Windhoek'  =>  '(UTC+02:00) Windhoek',
	'Africa/Harare'  =>  '(UTC+02:00) Harare',
	'Asia/Kuwait'  =>  '(UTC+03:00) Kuwait, Riyadh',
	'Asia/Baghdad'  =>  '(UTC+03:00) Baghdad',
	'Africa/Nairobi'  =>  '(UTC+03:00) Nairobi',
	'Europe/Moscow'  =>  '(UTC+03:00) Moscow, Volgograd',
	'Asia/Tehran'  =>  '(UTC+03:30) Tehran',
	'Asia/Tbilisi'  =>  '(UTC+04:00) Tbilisi',
	'Asia/Muscat'  =>  '(UTC+04:00) Abu Dhabi, Muscat',
	'Asia/Baku'  =>  '(UTC+04:00) Baku',
	'Asia/Yerevan'  =>  '(UTC+04:00) Yerevan',
	'Asia/Karachi'  =>  '(UTC+05:00) Islamabad, Karachi',
	'Asia/Tashkent'  =>  '(UTC+05:00) Tashkent',
	'Asia/Kolkata'  =>  '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
	'Asia/Colombo'  =>  '(UTC+05:30) Sri Jayawardenepura',
	'Asia/Katmandu'  =>  '(UTC+05:45) Kathmandu',
	'Asia/Dhaka'  =>  '(UTC+06:00) Dhaka',
	'Asia/Almaty'  =>  '(UTC+06:00) Almaty',
	'Asia/Yekaterinburg'  =>  '(UTC+06:00) Ekaterinburg',
	'Asia/Rangoon'  =>  '(UTC+06:30) Yangon (Rangoon)',
	'Asia/Novosibirsk'  =>  '(UTC+07:00) Novosibirsk',
	'Asia/Bangkok'  =>  '(UTC+07:00) Bangkok, Jakarta',
	'Asia/Brunei'  =>  '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
	'Asia/Krasnoyarsk'  =>  '(UTC+08:00) Krasnoyarsk',
	'Asia/Ulaanbaatar'  =>  '(UTC+08:00) Ulaan Bataar',
	'Asia/Kuala_Lumpur'  =>  '(UTC+08:00) Kuala Lumpur, Singapore',
	'Asia/Taipei'  =>  '(UTC+08:00) Taipei',
	'Australia/Perth'  =>  '(UTC+08:00) Perth',
	'Asia/Irkutsk'  =>  '(UTC+09:00) Irkutsk',
	'Asia/Seoul'  =>  '(UTC+09:00) Seoul',
	'Asia/Tokyo'  =>  '(UTC+09:00) Tokyo',
	'Australia/Darwin'  =>  '(UTC+09:30) Darwin',
	'Australia/Adelaide'  =>  '(UTC+09:30) Adelaide',
	'Australia/Canberra'  =>  '(UTC+10:00) Canberra, Melbourne, Sydney',
	'Australia/Brisbane'  =>  '(UTC+10:00) Brisbane',
	'Australia/Hobart'  =>  '(UTC+10:00) Hobart',
	'Asia/Vladivostok'  =>  '(UTC+10:00) Vladivostok',
	'Pacific/Guam'  =>  '(UTC+10:00) Guam, Port Moresby',
	'Asia/Yakutsk'  =>  '(UTC+10:00) Yakutsk',
	'Etc/GMT-11' => '(UTC+11:00) Solomon Is., New Caledonia',
	'Pacific/Fiji'  =>  '(UTC+12:00) Fiji',
	'Asia/Kamchatka'  =>  '(UTC+12:00) Kamchatka',
	'Pacific/Auckland'  =>  '(UTC+12:00) Auckland',
	'Asia/Magadan'  =>  '(UTC+12:00) Magadan',
	'Pacific/Tongatapu'  =>  '(UTC+13:00) Nukualofa',

	'Summary' => 'Resumo',
	'Detail' => 'Detalhe',
	'LBL_USER_LIST_DETAILS' => 'Detalhes',

	'LBL_OLD_PASSWORD' => 'Senha antiga',
	'LBL_CHANGE_PASSWORD' => 'Alterar senha',
	'LBL_NEW_PASSWORD' => 'Nova senha',
	'LBL_CONFIRM_PASSWORD' => 'Confirmar senha',
	'LBL_CHANGE_ACCESS_KEY' => 'Alterar chave de acesso',
	'LBL_ACCESS_KEY_UPDATED_SUCCESSFULLY' => 'Chave de acesso atualizada com sucesso',
	'LBL_FAILED_TO_UPDATE_ACCESS_KEY' => 'Falha ao atualizar a chave de acesso',
	'LBL_TRANSFER_OWNERSHIP' => 'Transferir proprietário',
	'LBL_LOGIN_AS' => 'Login como ',
	'LBL_USER_DELETED_SUCCESSFULLY' => 'Usuário excluído com sucesso',
	'LBL_ACTIVE_USERS' => 'Usuários ativos',
	'LBL_INACTIVE_USERS' => 'Usuários inativos',
	'LBL_CREATE_USER' => 'Criar usuário',
	'LBL_DELETE_USER_PERMANENTLY' => 'Excluir usuário permanentemente',
	'LBL_DELETE_USER_PERMANENTLY_INFO' => 'A exclusão permanente de um usuário transferirá todos os registros, incluindo comentários e histórico, para o novo usuário.',
	'LBL_RESTORE' => 'Restaurar',
	'LBL_USER_RESTORED_SUCCESSFULLY' => 'Usuário restaurado com sucesso',

	//Login strings
	'LBL_TO_CRM' => 'Login no Vtiger CRM',
	'LBL_INVALID_USER_OR_PASSWORD' => 'Nome de usuário ou senha inválido.',
	'LBL_INVALID_USER_OR_EMAIL' => 'Nome de usuário ou endereço de e-mail inválido.',
	'LBL_EMAIL_SEND' => 'Enviamos a você um e-mail para redefinir sua senha.',
	'Esqueci a senha' => 'Esqueci a senha',
	'LBL_CONNECT_WITH_US' => 'Conectar-se conosco',
	'LBL_GET_MORE' => 'Obtenha mais do Vtiger',

	'LBL_TRANSFER_RECORDS_TO_USER' => 'Transferir registros para usuário',
	'LBL_USER_TO_BE_DELETED' => 'Usuário a ser excluído',
	'LBL_ALMOST_THERE' => 'Quase lá!',
	'LBL_ABOUT_ME' => 'Sobre mim',
	'LBL_WE_PROMISE_TO_KEEP_THIS_PRIVATE' => '(Prometemos manter isso privado)',
	'LBL_ALL_FIELDS_BELOW_ARE_REQUIRED' => '(Todos os campos abaixo são obrigatórios)',
	'LBL_GET_STARTED' => 'Começar',
	'LBL_YOUR_CONTACT_NUMBER' => 'Seu número de contato',
	'LBL_WHERE_ARE_YOU_FROM' => 'De onde você é?',
	'LBL_SELECT_COUNTRY' => 'Selecionar país',
	'LBL_COMPANY_SIZE' => 'Tamanho da empresa',
	'LBL_JOB_TITLE' => 'Título do Cargo',
	'LBL_DEPARTMENT' => 'Departamento',
	'LBL_BASE_CURRENCY' => 'Moeda base',
	'LBL_CHOOSE_BASE_CURRENCY' => 'Escolha a moeda base',
	'LBL_OPERATING_CURRENCY' => 'A moeda base não pode ser modificada posteriormente. Selecione sua moeda operacional',
	'LBL_LANGUAGE' => 'Idioma',
	'LBL_CHOOSE_LANGUAGE' => 'Escolher idioma',
	'LBL_CHOOSE_TIMEZONE' => 'Escolher fuso horário',
	'LBL_DATE_FORMAT' => 'Formato de data',
	'LBL_CHOOSE_DATE_FORMAT' => 'Escolher formato de data',
	'LBL_PHONE' => 'Telefone',
	'Space' => 'Espaço',

	//picklist values for Default Calendar View field in MyPreference Page
	'ListView' => 'Visualização de lista',
	'MyCalendar' => 'Meu calendário',
	'SharedCalendar' => 'Calendário compartilhado',

	'LBL_CHANGE_OWNER' => 'Alterar proprietário',
	'LBL_TRANSFER_OWNERSHIP' => 'Transferir propriedade',
	'LBL_TRANSFER_OWNERSHIP_TO_USER' => 'Transferir propriedade para usuário',
	'LBL_OWNERSHIP_TRANSFERRED_SUCCESSFULLY' => 'Proprietário do CRM alterado com sucesso',
	'LBL_OWNERSHIP_TRANSFERRED_FAILED' => 'Falha ao alterar o proprietário do CRM',

	'Account Owner' => 'Proprietário da conta',
	'Starting Day of the week' => 'Dia de início da semana',
	'Day starts at' => 'O dia começa às',
	'Default Event Status' => 'Status padrão do evento',
	'Default Activity Type' => 'Tipo de atividade padrão',
	'Default Record View' => 'Exibição de registro padrão',
	'Left Panel Hide' => 'Ocultar Painel Esquerdo',
	'Row Height' => 'Altura da linha',

	//Change Username labels
	'LBL_CHANGE_USERNAME' => 'Alterar nome de usuário',
	'LBL_USERNAME_CHANGED' => 'Nome de usuário alterado com sucesso',
	'ERROR_CHANGE_USERNAME' => 'Erro ao alterar nome de usuário. Por favor tente mais tarde',

	'LBL_RESTORE_USER_FAILED' => 'Falha ao restaurar usuário. Já existe um usuário CRM com este nome de usuário.',

	'LBL_DUPLICATE_USER_EXISTS' => 'Usuário já existe',

	/* For Vtiger7*/
	'LBL_USERS_SETTINGS' => 'CONFIGURAÇÕES DE USUÁRIOS',
	'LBL_TEMPLATES' => 'Modelos',
);

$jsLanguageStrings = array(

	//Curency seperator validation messages
	'JS_ENTER_OLD_PASSWORD' => 'Por favor, digite sua senha antiga.',
	'JS_ENTER_NEW_PASSWORD' => 'Por favor, digite sua nova senha.',
	'JS_ENTER_CONFIRMATION_PASSWORD' => 'Por favor, digite sua confirmação de senha.',
	'JS_REENTER_PASSWORDS' => 'Por favor, digite novamente as senhas. Os valores \"nova senha\" e \"confirmar senha\" não correspondem.',
	'JS_INVALID_PASSWORD' => 'Você deve especificar um nome de usuário e senha válidos.',
	'JS_PASSWORD_CHANGE_FAILED_1' => 'Falha na alteração da senha do usuário para ',
	'JS_PASSWORD_CHANGE_FAILED_2' => ' falhou. A nova senha deve ser definida.',
	'JS_PASSWORD_INCORRECT_OLD' => 'Senha antiga incorreta especificada. Digite novamente as informações de senha.',
	'JS_ENTERED_CURRENT_USERNAME_MSG' => 'Você digitou o nome de usuário atual. Insira um novo nome de usuário.',
	'JS_NEW_ACCESS_KEY_REQUESTED' => 'Nova chave de acesso solicitada',
	'JS_CHANGE_ACCESS_KEY_CONFIRMATION' => 'Você solicitou uma nova chave de acesso.&lt;br&gt;&lt;br&gt;Com a nova provisão de chave de acesso, você deve substituir a chave de acesso antiga pela nova em todas as extensões instaladas.&lt;br&gt ;&lt;br&gt;Deseja continuar?',
);